---
- name: Ensure RabbitMQ config directory exists
  ansible.builtin.file:
    path: "{{ rabbitmq_conf_dir }}"
    state: directory
    owner: rabbitmq
    group: rabbitmq
    mode: "0750"

- name: Deploy rabbitmq.conf
  ansible.builtin.template:
    src: rabbitmq.conf.j2
    dest: "{{ rabbitmq_conf_file }}"
    owner: rabbitmq
    group: rabbitmq
    mode: "0640"
  notify: Restart rabbitmq-server
